spring:

  datasource:
    url: jdbc:postgres://nrspjldvvtpmwg:5bf28960227b6dee647e6da9ec7bfc66895c754908a310611039f5972304abb5@ec2-44-199-158-170.compute-1.amazonaws.com:5432/deva5hi3gmahml
    username: nrspjldvvtpmwg
    password: 5bf28960227b6dee647e6da9ec7bfc66895c754908a310611039f5972304abb5
    pool-size: 30

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
